---
title: "Economic Investment"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---
```{r}
library(tidyverse)
library(plotly)
library(leaflet)

#Set global theme for plots
theme_set(theme_minimal() + 
            theme(legend.position = "bottom", 
                  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)))
#Set options for all plots
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
  
Questions:
* When was original and revised market value documented? Do we know what this money is intended for?
  
  
```{r}
property_data =
  read_csv("./data/final_df.csv") %>%
  select(community_board, borough, overall_pop, poverty, rent_burden, garden_name, avg_org_value, avg_rev_value, avg_tot_appropriated, latitude, longitude) %>% 
  mutate(value_diff = avg_rev_value - avg_org_value)

num_gardens = 
  property_data %>% 
  drop_na(garden_name) %>% 
  group_by(community_board) %>% 
  summarize(garden_num = n())

unique_comboard =
  property_data %>% 
  distinct(community_board, .keep_all = TRUE)

property_data_final =
  left_join(unique_comboard, num_gardens, by = "community_board") %>% 
  select(-garden_name)
  
```


Row 
-------------------------------------
    
### Chart 1
    
```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain = property_data$avg_tot_appropriated)

property_data %>%
  mutate(
    click_label =
      str_c("<b>", garden_name, "</b><br>Budget: $", avg_tot_appropriated, "<br>", rent_burden, "% of income to pay rent", "<br>", poverty, "% poverty")) %>% 
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~longitude, ~latitude, radius = .1, color = ~pal(avg_tot_appropriated), popup = ~click_label)
```
   
Row {.tabset .tabset-fade}
-------------------------------------
   
### Chart 2

```{r}
  property_data_final %>% 
   ggplot(aes(x = community_board, y = value_diff, label = borough)) +
    geom_segment(aes(x = community_board, xend = community_board, y = 0, yend =  value_diff, color = borough), size = 1.3, alpha = 0.9) +
    theme_light() +
    theme(
      panel.border = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()) +
    labs(
      title = "How has the market value changed over time?",
      x = "Community Board",
      y = "Change in Value"
    )
```   
 
### Chart 3
    
```{r}

```