---
title: "Report"
output: 
  html_document:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}

library(tidyverse)
library(plotly)
library(leaflet)
library(ggridges)

#Set global theme for plots
theme_set(theme_minimal() + 
            theme(legend.position = "bottom", 
                  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)))
#Set options for all plots
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r include=FALSE}
garden =
  read_csv("./data/final_df.csv") %>%
  group_by(community_board) %>%
  select(community_board, borough, overall_pop, race_white:college_higher, garden_name:longitude)

garden_num = 
  garden %>% 
  drop_na(garden_name) %>% 
  group_by(community_board) %>% 
  summarize(garden_num = n())

garden_tidy = 
  left_join(garden, garden_num, by = "community_board")

```


### Number of gardens by Community Board

```{r, echo = FALSE, warning = FALSE}
number_borough = 
  garden_tidy %>% 
  select(community_board, garden_num, borough) %>% 
  distinct() %>% 
  mutate(
    community_board = as.factor(community_board)
  )


number_borough[is.na(number_borough)] <- 0 

number_borough %>%
  mutate(text_label = str_c("Number of Gardens: ", garden_num, "\nBorough: ", borough)
         ) %>% 
    plot_ly(
      x = ~community_board, y = ~garden_num, text = ~text_label, color = ~borough, 
      type = "bar", colors = "viridis"
            ) %>% 
        layout(autosize = F, width = 900, xaxis = list(
          title = "Community Board", tickmode = "linear"), yaxis = list(title = "Number of Community Gardens", dtick = 5))
```









